### ISSUE TITLE
eye and gaze tracking in opencvsharp

### ISSUE THREAD

**Issue by doctorwho-123** [shimat/opencvsharp#1084]
Hi, I want to understand that part of the screen, for example, the computer that the user's eye is looking at. I mean, I want the eye to act like a mouse. Wherever the eye moves, the mouse pointer moves as well. How to write this program in C # language and image processing and webcam and opencvsharp library. Does Libray openvsharp . have an example for eye tracking?

**Comment by A00107408** [comment]
OpenFace: https://github.com/TadasBaltrusaitis/OpenFace, is free and has eye tracking estimation. You need to build it in Visual Studio 2017. Once you have the FeatureExtraction.exe, you can call it from Unity with:

 //Launch OpenFace FeatureExtraction programatically.
private Process gaze = new Process();
string arg = " -q -g -3Dfp -aus -pose -gaze -device 0 -of \" OutPutFileName";
gaze.StartInfo.Arguments = arg;
gaze.StartInfo.CreateNoWindow = true;
gaze.StartInfo.UseShellExecute = false;
gaze.Start();

The OutPutFileName output file will be a .csv which you can open in Excel to see the user's eye gaze.

**Comment by doctorwho-123** [comment]
It is possible to learn step by step through the image or possibly make a video. I am a beginner.

**Comment by doctorwho-123** [comment]
thank you . It is possible to learn step by step through the image or
possibly make a video. I am a beginner.

**Comment by doctorwho-123** [comment]
@A00107408  What do you think about this algorithm? Does the algorithm detect the eye? https://github.com/Star-Clouds/CenterFace  . What is the difference between the algorithms of the two? https://github.com/TadasBaltrusaitis/OpenFace and https://github.com/cmusatyalab/openface

**Comment by yangzhongke** [comment]
I have worked on this topic for weeks. I ended up failing. Because I think it's impossible to perform high-accurate gaze tracking with ordinary webcam. Typical eye trackers are equipped with several near-infrared emitters, which can illuminate the eye to identify the pupil’s position and diameter . 
Furthermore, the algorithm of the eye-trackers has been improving for decades. The eye is a very complex system. For example, pupil movement and attention movement are not simply linear, and there are saccades between fixations. 
Then, I tried WebGazer.js, which is a full-fledged webcam eye-tracking library developed by Brown University and Pomona College. After calibration, WebGazer.js can achieve more precise effects. However, the precision of WebGazer.js is just about
100px (Dimri, 2018), and the accuracy at the edge of the screen is lower; therefore, WebGazer.js is not accurate enough for web evaluation.
So I suggest you turn to dedicated eye tracking device, like Tobii.
