### ISSUE TITLE
OpenCVSharp Tracker

### ISSUE THREAD

**Issue by bobdavies2000** [shimat/opencvsharp#1131]
# Summary of your issue

The OpenCVSharp Tracker interface has been redone and I would like to switch to using the new interface.  Is there an example of how to use the new Tracker?  The documentation still reflects the previous version of the tracker interface.  I will try to stumble through using the auto completion for now...

# Environment

Windows 10 latest with Visual Studio 2019.  I am using the 12/29/20 release that just arrived this morning.

# What did you do when you faced the problem?

I have commented out my code for the tracker so that I could continue to use the latest release of OpenCVSharp.

## Example code:

Public tracker As cv.Tracking.MultiTracker ' multiTracker is not found

## Output:

not applicable.

## What did you intend to be?

not applicable.

**Comment by shimat** [comment]
I updated the OpenCvSharp API documentation. http://shimat.github.io/opencvsharp/api/OpenCvSharp.html

The MultiTracker class has been removed in OpenCvSharp 4.5.1 because that module is obsolete in OpenCV 4.5.1 (MultiTracker has been moved to a file named `legacy`). Sorry but I don't know what the alternative is.
https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/include/opencv2/tracking/tracking_legacy.hpp#L58
