### ISSUE TITLE
OpenCvSharp.CPlusPlus not available anymore?

### ISSUE THREAD

**Issue by ana2404** [shimat/opencvsharp#1249]
Hi everyone,

I am trying to recover an old project I had where I used an old, already deprecated, version of OpenCvSharp. There, I could easily write

using OpenCvSharp.CPlusPlus;

and use many structures from opencv. However, in this newer version there seems not no be a CPlusPlus namespace and I am confused as to how to proceed then. How do I access to structures such as Point2f or CvPoint in this newer version?

Thanks in advance,
Ana.

**Comment by shimat** [comment]
`OpenCvSharp.CPlusPlus` has been renamed `OpenCvSharp`, because the native OpenCV C API is almost obsolete, and the C++ API has become more common.

OpenCvSharp 2.x | OpenCvSharp 3.x and later
------------ | -------------
OpenCvSharp | (deleted)
OpenCvSharp.IplImage | (deleted)
OpenCvSharp.CvPoint | (deleted)
... | ...
OpenCvSharp.CPlusPlus | OpenCvSharp 
OpenCvSharp.CPlusPlus.Point2f | OpenCvSharp.Point2f 
OpenCvSharp.CPlusPlus.Mat | OpenCvSharp.Mat
... | ...

**Comment by ana2404** [comment]
Thanks a lot! I had been struggling with that for a couple of days and now the answer makes a lot of sense.

I tried and it seems to work just fine. I'll change the code then the entire code to the new C++ API then, which seems to be the main problem here.
