### ISSUE TITLE
Mac OS 11.4 Unable to load shared library 'OpenCvSharpExtern'

### ISSUE THREAD

**Issue by khinklenj** [shimat/opencvsharp#1278]
# Summary of your issue
I am getting the following error when try to run a simple code

Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies

# Environment
Mac OS 11.4

# What did you do when you faced the problem?
I get the above error when the code below

## Example code:
try
{ 
   Mat mat = new Mat();
}
catch(Exception err)
{
   Console.WritleLine(err);
}

## Output:
Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies

**Comment by exverse** [comment]
Put the DLL in your bin folder with your executable.

**Comment by liviaerxin** [comment]
I have tested and used `OpenCvSharp` in Mac OS 11.4  in `Rosetta` in `Apple Silicon` successfully. It may be caused by `OpenCvSharpExtern.dylib` failing to open its other `dependencies`, like:

```sh
dyld: loaded: <83AAF35B-E6AE-3AEB-9EE5-9614C3EA8883> /usr/local/opt/freetype/lib/libfreetype.6.dylib
dyld: loaded: <1A213374-9626-328B-8379-8A24C2108073> /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
dyld: loaded: <A90F722E-B570-3D08-802D-2F3B1DFEEC58> /usr/local/opt/tesseract/lib/libtesseract.4.dylib
dyld: loaded: <5701AB53-D57D-38AE-8E76-ADBC03205B84> /usr/lib/libcurl.4.dylib
dyld: loaded: <02072211-32BD-3465-9614-CD73A0A0E661> /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib
```

You can test whether it's able to load `OpenCvSharpExtern.dylib` by using the simple code [dlopen_test](https://gist.github.com/liviaerxin/38713f488ee3dc262581ff7c433cc6d9#file-dlopen_test-c). 

```sh
DYLD_PRINT_LIBRARIES=1 ./dlopen_test.out /Users/{your libOpenCvSharpExtern.lib path}/libOpenCvSharpExtern.dylib
```

If you failed to load the library, the easy way to install other dependencies is using `Homebrew` in `Rosetta`(**!!important**, must not be in Native).
`brew install opencv` will install the required dependencies to the right locations `/usr/local/` or `/usr/lib`.
