### ISSUE TITLE
Find multiple results with MatchTemplate

### ISSUE THREAD

**Issue by jimjonesGIT** [shimat/opencvsharp#129]
Hi,

I am using the following code to find an image inside an image:

Mat src = OpenCvSharp.Extensions.BitmapConverter.ToMat(Resources.all);
Mat template = OpenCvSharp.Extensions.BitmapConverter.ToMat(Resources.img);
Mat result = src.MatchTemplate(template, TemplateMatchModes.CCoeffNormed);

double minVal, maxVal;
OpenCvSharp.Point minLoc, maxLoc;
result.MinMaxLoc(out minVal, out maxVal, out minLoc, out maxLoc);
Console.WriteLine("maxLoc: {0}, maxVal: {1}", maxLoc, maxVal);

How can expand the code to find all occurences of an image inside an image, not only the first occurance?

Thank you!

**Comment by shimat** [comment]
I guess... the most simple way is that you should access all pixels of `result` to get similarity ratio, and decide if the ratio value is sufficiently high. 

(I don't debug the following code.)
```c#
// the type of result is probably CV_32FC1
var indexer = result.GetGenericIndexer<float>(); 

var occurencePoints = new List<Point>();
for (int r = 0; r < result.Rows; r++)
{
    for (int c = 0; c < result.Cols; c++)
    {
        float similarity = result[r, c];
        if (similarity > 0.8) // specify your threshold for occurence
            occurencePoints.Add(new Point(c, r));
    }
}
```

**Comment by sirjimjones** [comment]
Thank you. Now the recognition works great on every match!
Just a quick question: Do you know how to speed up the recognition? I have tried emucv before and the recognition was almost instant. With opencvsharp it takes about 1 second to find an image (24x24) in an image (1920x1080).
Maybe there is a way to run in on the GPU instead of the CPU?

Here is my complete source code:

Mat src = OpenCvSharp.Extensions.BitmapConverter.ToMat(imgFull);
Mat template = OpenCvSharp.Extensions.BitmapConverter.ToMat(img);
Mat result = src.MatchTemplate(template, TemplateMatchModes.CCoeffNormed);
var indexer = result.GetGenericIndexer<float>();

for (int r = 0; r < result.Rows; r++)
{
	for (int c = 0; c < result.Cols; c++)
	{
		float similarity = indexer[r, c];
		if (similarity > threshold)
		{
			Rectangle destRect = new Rectangle(c, r, img.Width, img.Height);
			//do something
		}
	}
}

**Comment by sirjimjones** [comment]
Thanks! Works great. I am running the outer loop in a Parallel.For loop which speeds up the whole process.
