### ISSUE TITLE
SURF&SIFT do not work.

### ISSUE THREAD

**Issue by 1102163785** [shimat/opencvsharp#146]
When I call "SIFT.Create()",the Debugger catch a "System.EntryPointNotFoundException" and tells me that the application can't find an entrypoint named "xfeatures2d_SIFT_create" in "OpenCvSharpExtern.dll".Class SURF do the same.Is that part cannot work yet?

**Comment by shimat** [comment]
In OpenCV 3.0, SIFT and SURF features moved to the external module `contrib`.
https://github.com/itseez/opencv_contrib

OpenCvSharpExtern does not contain contrib, so you cannot use SIFT and SURF.

**Comment by 1102163785** [comment]
Got it.Thanks.

**Comment by fdncred** [comment]
@1102163785 You should try Kaze and Akaze.  I have found that they work must better than SIFT and SURF and are not encumbered by the licensing issues SURF is.

**Comment by 1102163785** [comment]
Yeah,they does, thank you.
And I have another question : how can I compare two pictures and get their similarity?
I know "Cv2.CompareHist()" but I whant calculate the similarity using key points.

**Comment by fdncred** [comment]
@1102163785 I don't have any code written in OpenCvSharp yet to do this but it's essentially the same as SURF/SIFT.

1. Load image files
2. Create keypoints and descriptors for each image
3. Use a bruteforcematcher to compare the descriptors and output a vector of matches.
4. VoteForUniqueness of the vector of matches
5. VoteForSizeAndOrientation using the keypoints and vector of matches
6. At this point you can usually generate a homography based on matched features
7. Then usually you use the Nearest Neighbor Distance Ratio to determine which matches are good.  I usually use this "goodMatches / allMatches" to get a percentage of match.

Kaze/Akaze are better this way because there are many more keypoints than with SIFT/SURF.

The great thing about OpenCvSharp is it's pretty easy to port C/C++ code to it.  So you should be able to google a solution in C/C++ and port it.  I'm betting it'll pretty closely match my bullets above.

Another approach is just to follow @shimat 's KazeSample.cs and then jump off into my bullets.

Hope this helps.

**Comment by 1102163785** [comment]
@fdncred They do help, thanks a lot.The methods VoteForUniqueness and VoteForSizeAndOrientation are in EmguCV, and I found an example here http://www.emgu.com/wiki/index.php/SURF_feature_detector_in_CSharp

**Comment by fdncred** [comment]
Yes, I also have a SURF demo based off this example and EMGU.  Good stuff.
