### ISSUE TITLE
unable to load in openCVSharp in iis hosted application

### ISSUE THREAD

**Issue by LightCZ** [shimat/opencvsharp#170]
I am on Windows 10 and Visual studio 2015 (if that matters - but i doubt it)
I created simple application to test my hypothesis with major problem with openCVsharp in application hosted in IIS (WCF service in my case)

Lets take following code:

``` csharp
public void GetData(){
      var imPath = "C:\\PathToImage\\Original.jpg";
      var image = Cv2.ImRead(imPath);
      var sift = new SIFT(100);
      KeyPoint[] keypoints;
      MatOfFloat descriptors = new MatOfFloat();            
      sift.Run(image, null, out keypoints, descriptors);
    }
```

I battle with cannot external library and i copy proper version from dll/x{arghitecture} to my bin (build) directory.

When i solve this i can go to the line when SIFT instancing and i receive following exception
An exception of type 'System.Runtime.InteropServices.SEHException' occurred in OpenCvSharp.CPlusPlus.dll but was not handled in user code

This is all - no further detail enclosed.
So far i was unable to use opencvsharp in IIS hosted application

**Comment by fdncred** [comment]
@LightCZ The key to using OpenCvSharp with IIS or any other solution is to:
1. Make sure you're using the latest OpenCvSharp and OpenCV.
2. Make sure you have the VisualC++ redistrubtables installed.
3. Make sure the user that IIS is running under has a path variable that contains the directory of all your DLLs (OpenCvSharp and OpenCV).  Your app has to be able to find all its dependencies.  Depends.exe can help if you run it under the IIS user environment.
4. When you get to SIFT, don't use it.  Use Kaze as I mentioned before in #146 and #158.

**Comment by LightCZ** [comment]
Thanks man but:
1. I can run opencv without any problems in lets say console application so - VisualC++ is out.
2. I am using latest version of openCVSharp 2.xxx because SIFT is not present in 3.xxx version
3. I copy all DLLs to my bin directory - I had issue with that (actually it fell on the CV2.ImRead... line when you have not found issue).

**Comment by fdncred** [comment]
@LightCZ I'd suggest taking a look at this code https://github.com/shimat/opencvsharp/blob/f53cbe43e2b88effd7341b810917aa8fcfaaa09e/src/OpenCvSharp/Util/WindowsLibraryLoader.cs because it is the code loading the libraries. There is a specific part about IIS/ASP.Net in that code but it looks like it's not being used.

I noticed in v3 that it seems that OpenCvSharp wants to load the native dlls out of a path like dll\x64\dll_file_name.  So once i created that structure things started working but I'm not sure 2.x is like that.

One thing you could do is add logging to this file so at least you know where OpenCvSharp is trying to load files from.

The only reason i suggested Kaze is because SIFT and SURF both require licensing to use and, in my opinion, Kaze and Akaze are better due to more unique keypoints found plus it's a bit faster in my testing.

Good luck.

**Comment by LightCZ** [comment]
I know about that class - i fixed my DLL load by reverse-engineering that windowsLibraryLoader class.
Sift and SURF are patended only on US soil and since i am from europe - and target usage is europe its ok here. I made extensive testing of many algorithms SIFT / SURF / Kaze / AKaze and i am not prepared to throw SIFT overboard. I am really really convinced that it is some kind of bug in this library.

**Comment by fdncred** [comment]
@LightCZ ok. just trying to help.  maybe i'll try your code snippet in 2.x and see if i get the same error.

**Comment by LightCZ** [comment]
thanks man - its like 3 minute work. But i can reproduce this bug on 3 different computers and even on Windows 8.1 / Windows 10

**Comment by fdncred** [comment]
@LightCZ I just downloaded the 2.x code base, added the CppStyleSamplesCS.csproj and SampleBase.csproj to the src distribution so i could step through the LoadLibrary part.  

Then i made sure the sample project was pointing to the SiftSurfSample.cs sample code in order to try SIFT and SURF.  I then had to create the directory structure CppStyleSamplesCS\bin\x86\Debug\dll\x86 and copy these dlls to that directory - msvcr120.dll, msvcp120.dll, opencv_*2410.dll, and OpenCvSharpExtern.dll.  Of course the OpenCvSharp assemblies are in CppStyleSampleCS\bin\x86\Debug.

I was able to run the sample code without any changes once i got the dlls in the proper places. Everything worked as expected.

I realize this doesn't match your codebase but it's a know working sample that utilizes SIFT and SURF. The only two things different I see in your code above versus the sample code is that @shimat converts to gray first in his sample code and 100 in the SIFT(100) but i assume the 100 isn't causing a problem.  

Not sure any of this is helpful.

I'm using Visual Studio 2013 and Windows 10 v1511.

**Comment by LightCZ** [comment]
And do you run this working solution in IIS ?

**Comment by fdncred** [comment]
@LightCZ it's not an IIS solution, so no, i did not. Post your IIS solution somewhere and I'll help debug it.

**Comment by LightCZ** [comment]
Its easy to reproduce. Simply create new WCF application in visual studio and copy and paste my code inside... any method. Also add opencvsharp from nuget F5 and wholaa. But i will post my solution with that - give me 10 min.

**Comment by LightCZ** [comment]
https://github.com/LightCZ/OpenCVSharp-IISUsage  
Sample bug recreation in IIS. Invoke that service with... WCFTestclient or any client of your choice. Also dont forget to change imPath to any image you have on disk. And copy bin/debug/dll/XXX/ content  to your /bin/debug/ directory where XXX is your architecture.

**Comment by fdncred** [comment]
@LightCZ No problems. You can see in my screenshot that i'm debugging and the keypoints and descriptors are populated.  The trick was to put the dll folder in the "right" directory because by default it never found the dlls properly.

So I have the dll\x86 directory with all the dependencies right under TestOpenCvSharp.  Everything loads and runs there just fine.

It's worth noting that I'm using VS2013 *and* I added your project to the OpenCvSharp solution so I could step through the OpenCvSharp code to see where OpenCvSharp was trying to load the dependencies from. 

![out](https://cloud.githubusercontent.com/assets/343840/12308178/5087eefc-ba09-11e5-9677-5ebd488075f9.png)

**Comment by LightCZ** [comment]
Ok that works... i kinda dont know why because from my understanding of WindowsLibraryLoader class it should not matter which one will load the application. Now this will be major problem with building deployment package for this kind of application. I think i ll build custom opencv sharp with that uncommented that System.Web loader and going to hope it will work. Thanks for your help man

**Comment by fdncred** [comment]
@LightCZ There is an optional parameter to LoadLibrary in a variable called additionalPaths indicating there is some way to tell OpenCvSharp where to look for the dependencies.  If you could pass a separate directory path to LoadLibrary you'd have everything working.  I'm just not sure how to supply an additional path. 

@shimat How do you use the IEnumerable<string> additionalPath variable in LoadLibraries()?

**Comment by shimat** [comment]
```c#
static void Main()
{
    // set additionalPaths at the start of program
    WindowsLibraryLoader.Instance.AdditionalPaths.Add(@"C:\foo\bar");

    // native DLLs should be loaded from C:\foo\bar at this line
    var mat = new Mat();
    ...
}
```

**Comment by LightCZ** [comment]
Ok that totally solved my problem. With this additionalPaths feature i managed to sideload version 2 and version 3 - i just had to build my custom version 2 with different namespace and different public key so i did fork of that repository and commit my changes there. Thanks everyone - and good library there i read almost all the code and its looking good.

**Comment by LightCZ** [comment]
Just to clarify - i think that WindowsLibraryLoader.Instance.AdditionalPaths dont work in 2.x branch
