### ISSUE TITLE
Iterative Closest Point (ICP)

### ISSUE THREAD

**Issue by xiongxao** [shimat/opencvsharp#252]
Hello, I'm trying to match and morph a model to a template using Iterative Closest Point (ICP) like the following URLs below.  How would I use this wrapper to do it?  Thanks for your help.

http://docs.opencv.org/3.0-beta/modules/surface_matching/doc/surface_matching.html#pose-registration-via-icp

http://www.morethantechnical.com/2010/06/06/iterative-closest-point-icp-with-opencv-w-code/

**Comment by hmongware** [comment]
Any timeframe on when this will be added and when the next release date will be?  I am also interested in the surface matching module.

**Comment by Abdul-Mukit** [comment]
Is there any update? Has the surface_matching support been added? I am also working with ICP and would like to know. Thank you.

**Comment by nietras** [comment]
@shimat has anything happened regarding ICP support? Noticed that Emgu has this: https://www.emgu.com/wiki/files/4.5.1/document/html/e38e6b86-77a3-e894-f17a-ea4001468254.htm

**Comment by shimat** [comment]
Apologies for bringing this back after such a long time without a maintainer response. I am reopening it for consideration because the original request is still unresolved in OpenCvSharp5: the official build explicitly sets [`BUILD_opencv_surface_matching=OFF`](https://github.com/shimat/opencvsharp/blob/main/cmake/opencv_build_options.cmake#L42), and OpenCvSharp does not currently expose the `surface_matching` / ICP APIs.

This should be treated as a module-coverage feature rather than a usage question. A first implementation would need to decide the minimum useful ICP/PPF API surface, enable the module in supported native builds, add managed/native wrappers, and cover at least one registration round trip.
