### ISSUE TITLE
GPU Darknet detection not working

### ISSUE THREAD

**Issue by FlawTECH** [shimat/opencvsharp#450]
Hello,
I've been wondering if there's any update regarding #123 ?
I'm trying to use GPU based detection using ```CvDnn.ReadNetFromDarknet("yolo-voc.cfg", "yolo-voc.weights");``` but it only seems to be using the CPU.

In fact, when running ``int count = Cv2.GetCudaEnabledDeviceCount();`` it still returns 0 even though CUDA 9.1 is installed on the machine, so my guess is that it simply won't use GPU based detection and it's really annoying. I tried the solution mentioned in #123 but I don't even know where I'd need to put opencv_core and opencv_gpu dlls and it's probably outdated.

I'm running Windows 10 btw.
Thanks !

**Comment by ravazquez** [comment]
As far as I understand, openCV does not ship with CUDA enabled dlls, you have to build the dlls on your own to enable CUDA.  I also believe that the default OpenCVSharp binaries do not ship with CUDA enabled, you may need to add the references to your own openCV dlls in the OpenCVSharp project and rebuild it by hand.

**Comment by captainst** [comment]
I encountered the same problem. I noticed that the current version of opencvsharp uses the static libs from opencv rather than dlls. So the #123 solution probably won't work. I think for the current version, the correct steps should be like this:
1. Rebuild the opencv 3.4.1 with cuda support. (there are many tutorials on line on how to do this)
2. Download or clone the opencvsharp 3.4.1 source, replace the .lib files in opencv_files_341 folder with the newly generated .lib files with cuda support.
3. Rebuild the opencvsharp from source.

Haven't tried this yet. But I think that should be the right way.
