### ISSUE TITLE
Mat Finalizer Missing?

### ISSUE THREAD

**Issue by hanseltime** [shimat/opencvsharp#540]
Using OpenCvSharp3-AnyCP 3.4.1.20180830 Nuget, I had wanted to have a few asynchronous tasks read operating on an OpenCV Mat that was returned from a single source. 

  The Matrix is constructed using new Mat( int rows, int columns, MatType type).

  I assumed that there was a finalizer in place for garbage collection to call Dispose() if the matrix went out of scope.  However, it doesn't seem to be the case, and I don't see a ~Mat finalizer in the source.

  Is there a reason for not having a finalizer on Mat?

**Comment by shimat** [comment]
The base class of Mat has its finalizer (destructor).

However, in C#, destructor behavior (GC behavior) may be different from your understanding.

**Comment by MHerrmannSOLID** [comment]
There are 3 reason why GC is called (https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#conditions_for_a_garbage_collection):

-The system has low physical memory. 
-The memory that is used by allocated objects on the managed heap surpasses an acceptable threshold.
-The GC.Collect method is called.

Since usually most of the memory of "Mat" is allocated in the unmanaged space, GC simply doesn’t see it.
So if you do not additionally allocate much manged memory in your program, GC will not run. Hence you should consider calling it "manually" by GC.Collect() once in a while.

**Comment by hanseltime** [comment]
Thanks for the clarification.  I should've realized that the unmanaged memory was piling up too quickly while GC wasn't seeing a need to do any garbage collection so I was filling up my heap.  

Looks like all my code will need to be more explicit about calling release/dispose.  So much for being lazy about it.

**Comment by shimat** [comment]
Using `GC.AddMemoryPressure` is one solution. However, since the method is mutual exclusion, a performance degradation may occur on multi-threaded environment. 
And it is difficult to always monitor the amount of memory used by Mat.

https://docs.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure?view=netframework-4.7.2

**Comment by HanJunJun** [comment]
Is there a better solution for this bug?
Except gc
