### ISSUE TITLE
Using Docker - Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies

### ISSUE THREAD

**Issue by HEBOS** [shimat/opencvsharp#694]
# Summary of your issue
My project is using video capture.
I'm using Docker.
Everything works fine on Windows, but not using Linux Docker.

# Environment
.NET Core 3.0
Visual Studio 2019
Docker 2.0.0.3 (31259)
Linux containers

# What did you do when you faced the problem?
F5 - Debugging the project

## Example code:
```
var capture = new VideoCapture("some video source")
```
## Output:

```
DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
```

## What did you intend to be?
Start video capturing.
It works if I run the C# project directly, but if I use Docker Compose, it starts running but raises an exception, that it is not able to find some dependencies.
Note that I haven't put anything in DockerFile. I'm not sure if I need to force Docker to install OpenCV as a dependency. If yes, I don't know how, so it would be useful if I could get some advice on this too.

**Comment by EeeasyBreezy** [comment]
OpenCvSharpExtern.dll requires libOpenCvSharpExtern.so library under linux.
You need to install the whole OpenCv to satisfy libOpenCvSharpExtern.so
Installation of opencv can be very time consuming since you have to build it from source 

I would recommend to use an opencv sharp docker image to build your custom image from

https://hub.docker.com/r/dockeratso/ubuntu-opencv4-dotnet/tags

You still need to copy libOpenCvSharpExtern.so to /lib folder of resulting image
