### ISSUE TITLE
Memory Leaks... when I did "mat -> Intptr -> mat"

### ISSUE THREAD

**Issue by YouMinJung** [shimat/opencvsharp#761]
Current I use c++ dll in c#. program flow is like below..

1) [c++] get some image, then **return the Mat data.**
2) [c# -1] get the data and then convert to Mat data **(IntPtr -> Mat)**
3) [c# -1] enqueue that image data. transfer that queue to second c# script.
4) [c# -2] get image data from first c# script.
5) [c# -2]  dequeue and then use that image

# Environment
Windows 10

# Example code:
## Here is the [c# - 1] Code

[DllImport("Camera_Connector")]
public static extern IntPtr GetImageFrame();

private Queue<Mat> OrigianlFrame = new Queue<Mat>();

// get mat format from camera
IntPtr image = GetImageFrame();

// conver intptr to mat
Mat frame = new Mat(image);

// store original frame in queue
OrigianlFrame.Enqueue(frame);

## Here is the [c# - 2] Code

// Image Processing ///
Mat copy_image = OriginalFrame.Dequeue();
. . . .
//////////////////////////

# Comments
When I execute the program, program quits just few minutes after.
I think that problem is memory leaks.
How can I solve this problem? Help me!!

**Comment by shimat** [comment]
Do you call `copy_image.Dispose();` ?

I do not recommend this method, because you may suffer from difficult and confusing errors. The OpenCV and C++ runtime versions of your C++ program must be the same as the OpenCvSharp's dependencies. It is desirable and safe to write all your programs in C++ or all in C#.

**Comment by YouMinJung** [comment]
I did use copy_image.Dispose() ... but still occurs the memory leaks....;;

**Comment by shimat** [comment]
Please check if memory leak occurs even if you erase all image processing code.
I can only say that you should call Dispose thoroughly. Calling GC.Collect regularly may also be effective. https://github.com/shimat/opencvsharp/issues/559

Or it may have failed to release cv::Mat memory due to a problem with C++ described above.
