### ISSUE TITLE
Updating to OpenCvSharp4 4.1.1.20191216 Mat.GetArray compilation error.

### ISSUE THREAD

**Issue by msavidg** [shimat/opencvsharp#799]
# Summary of your issue

After upgrading from "4.1.1.20191110" to "4.1.1.20191216" receive compilation error:

No overload for method 'GetArray' takes 2 arguments

# Environment

Windows 10, VS2019, .NET Framework 4.7.2

# What did you do when you faced the problem?

After upgrading to latest Nuget Package version "4.1.1.20191216"

## Example code:

```
            // grab the (x, y) coordinates of all pixel values that
            // are greater than zero, then use these coordinates to
            // compute a rotated bounding box that contains all
            // coordinates
            for (int r = 0; r < thresh.Rows; r++)
            {
                for (int c = 0; c < thresh.Cols; c++)
                {
                    var d = thresh.GetArray(r, c);
                    if (d[0] > 0.0000D)
                    {
                        coords.Add(new OpenCvSharp.Point(r, c));
                    }
                }
            }
```

## Output:

```

No overload for method 'GetArray' takes 2 arguments

```

**Comment by shimat** [comment]
I changed the specifications of GetArray. Because there are many misunderstandings about its specification. I'm sorry to confuse you.
Your code snippets are also based on misunderstandings. The old GetArray(r, c) gots the entire elements of Mat, with r, c as the upper-left coordinate. The new GetArray removes the upper left coordinate arguments. It always gets the entire elements of Mat.

(I don't debug the following code)
```c#
byte[,] bytes;
thresh.GetArray(out bytes);

for (int r = 0; r < thresh.Rows; r++)
{
    for (int c = 0; c < thresh.Cols; c++)
    {
        var d = bytes[r, c];
        if (d > 0.0000D)
        {
            coords.Add(new OpenCvSharp.Point(r, c));
        }
    }
}
```

**Comment by iiviad-mmaynard** [comment]
This code doesn't work either. The compiler says it can't identify the type of the output.
