### ISSUE TITLE
Nuget packet maybe have some bug

### ISSUE THREAD

**Issue by IOL0ol1** [shimat/opencvsharp#838]
OpenCvSharp4.Windows  v4.2.0.20200108
Windows 10
Visual stduio 2019

Create a WPF project(.Net Fromework 4.6.1)
Nuegt install OpenCvSharp4.Windows  v4.2.0.20200108 
add  some sample OpenCvSharp4 code in your wpf project(just make sure your program calls opencv4sharp).

-  right click solution in vs ,add your project to git source control with a default .gitignore file. push to remote.
-  create a new local folder to get code from remote.
-  Compile and run new code, You're going to have issue #818 ,because no **dll** folder in bin output.

Can only be reproduced on the Packages.config, PackagesReference is ok.

nuget packet script issuse?.
Copy **dll** folder only on first install nuget packet? or project folder path changed?

**Comment by ArXen42** [comment]
I tried to reproduce your bug, but did not encountered any problems, though I followed your path only roughly:

1. Created project (in JB Rider, but that shouldn't make a difference).
2. Added OpeCvSharp4.Windows through NuGet (`packages.config`).
3. Committed all files to git.
4. Cleaned all solution files, left only .git directory.
5. Restored committed files using `git checkout .`
6. Reopened project, it runned successfully, having all the neccessary dll's.

My default `.gitignore` though was simple:
```
bin/
obj/
/packages/
```

I guess your problem was either incorrect .gitignore or maybe Visual Studio did not save some files before commit. If you still have this problem, it would help if you create repro repository containing your test project (that has no dll in output) and post it here.

**Comment by IOL0ol1** [comment]
I think I found the reason.
use Packages.config  in visual studio may present this problem.
use PackageReference is ok.

**Comment by IOL0ol1** [comment]
> I tried to reproduce your bug, but did not encountered any problems, though I followed your path only roughly:
> 
> 1. Created project (in JB Rider, but that shouldn't make a difference).
> 2. Added OpeCvSharp4.Windows through NuGet (`packages.config`).
> 3. Committed all files to git.
> 4. Cleaned all solution files, left only .git directory.
> 5. Restored committed files using `git checkout .`
> 6. Reopened project, it runned successfully, having all the neccessary dll's.
> 
> My default `.gitignore` though was simple:
> 
> ```
> bin/
> obj/
> /packages/
> ```
> 
> I guess your problem was either incorrect .gitignore or maybe Visual Studio did not save some files before commit. If you still have this problem, it would help if you create repro repository containing your test project (that has no dll in output) and post it here.

 see above

**Comment by ArXen42** [comment]
I have cloned and tested your project in Visual Studio and Rider, everything worked.

![image](https://user-images.githubusercontent.com/10744285/75111523-e9024f00-564b-11ea-9c03-53c30b82dd4a.png)

**Comment by ArXen42** [comment]
@IOL0ol1 what is your CPU? There is some bug in latest versions of OpenCV that prevents it from working without AVX2 instruction set.

**Comment by IOL0ol1** [comment]
> @IOL0ol1 what is your CPU? There is some bug in latest versions of OpenCV that prevents it from working without AVX2 instruction set.

i7-9700k .
Perhaps this is not a general problem. After cloning from a remote, there is no native dll in my output directory.
This question should be closed if you see it later.
Thank you for your attention.
