### ISSUE TITLE
Strange artefacts on new Mat

### ISSUE THREAD

**Issue by alexgurenko** [shimat/opencvsharp#858]
Hello, all! 

I using 3.4.1.20180319 with framework 4.7.2

When i cretaed new mat as Mat test = new Mat(100, 200, MatType.CV_8UC1); or   Mat sss = new Mat(100, 200, MatType.CV_8SC1); i got such results:
![1](https://user-images.githubusercontent.com/39540518/73749475-0bf8bc00-478e-11ea-96af-44172a6982d4.jpg)
![sss](https://user-images.githubusercontent.com/39540518/73749482-10bd7000-478e-11ea-89d7-fe1d41ead198.jpg)

What is it problem? How to fix this?

**Comment by ravazquez** [comment]
Hi @alexgurenko, as far as I know when you create a new Mat like that you are just allocating new memory, those constructors do not guarantee that the memory is "clean". There should be a variant which lets you specify the Scalar color you want to be written to all pixels of the Mat if you need it to be "clean". Of course as soon as you write into the Mat (resulting from any OpenCV function) the dirty pixels will get overwritten, but if you are using the original new Mat against say boolean operators etc, it would be best for you to make sure that you initialize it so that all pixels have the initial value you expect.

Hope that clears things up a bit.

**Comment by alexgurenko** [comment]
> Hi @alexgurenko, as far as I know when you create a new Mat like that you are just allocating new memory, those constructors do not guarantee that the memory is "clean". There should be a variant which lets you specify the Scalar color you want to be written to all pixels of the Mat if you need it to be "clean". Of course as soon as you write into the Mat (resulting from any OpenCV function) the dirty pixels will get overwritten, but if you are using the original new Mat against say boolean operators etc, it would be best for you to make sure that you initialize it so that all pixels have the initial value you expect.
> 
> Hope that clears things up a bit.

Thanks, @ravazquez !

I already guessed ) 
  Mat mask = new Mat( item_input.Size(), MatType.CV_8UC1, new OpenCvSharp.Scalar(0)); fixes this problem

**Comment by ravazquez** [comment]
Glad you figured it out @alexgurenko, however you do not need to create a new Scalar object to do that, you can used any of the predefined Scalar entries in here: https://github.com/shimat/opencvsharp/blob/b0f011cdc574f3fce2fb6201265438a18363d53a/src/OpenCvSharp/Modules/core/Struct/Scalar.cs#L473

Like so:

Mat mask = new Mat( item_input.Size(), MatType.CV_8UC1, Scalar.Black);
