### ISSUE TITLE
Compiling to enable MSMF support?

### ISSUE THREAD

**Issue by GilchristT** [shimat/opencvsharp#869]
# Summary of your issue
Understanding how to compile with MSMF support

# Environment
Windows 10

Hi, not an issue but a question, apologies if this isn't the correct way to ask.

I want to use OpenCVSharp for a project but I need to have Microsoft Media Foundation support enabled, specifically to use VAAPI for a VideoWriter instance.

I understand that OpenCVSharp is compiled without MSMF enabled for various reasons. If I want to compile my own copy, is it OpenCVSharp I should be looking at or is it a case of compiling my own copy of OpenCV and dropping the relevant DLLs into place?

I've had a quick look through the code and can't see anywhere obvious that the underlying OpenCV compiler flags are set?

Thanks in advance.

**Comment by GilchristT** [comment]
Folks

I've tried to progress this on my own but I'm way out of my depth with regard to compiling C++ code and probably specifically with regard to linkers and includes. I've detailed the process I'm following below, I'd greatly appreciate it if anyone can point me towards where I'm going wrong?

Thanks

Download OpenCV 4.2.0 SRC from Github releases link (I figured it's better to use the 4.2.0 release rather than cloning the current branch from GitHub)
Extract to c:\OpenCV\opencv_src
Download OpenCV Contrib 4.2.0 src from releases
Extract to c:\OpenCV\opencv_contrib

Run CMake Gui
Set output dir to c:\OpenCV\opencv_bin
Use defaults other than 
	Setting "OPENCV_EXTRA_MODULES_PATH" to  c:\OpenCV\opencv_contrib\modules
	Enabling "WITH_MFX" (I want to test Intel QSV - have the Intel Media SDK installed and environment variables set)
	Enabling "BUILD_opencv_world"
	
CMake -> Generate -> Open Project

In Visual Studio 2019 
	Expand "CMakeTargets"
	Right-click on "ALL_BUILD" and select "Build" (Build environment defaults to "Debug" and x64)
	Right-click on "INSTALL" and select "Build"
	Change build environment to "Release"
	Repeat build for "ALL_BUILD" and "INSTALL" )is this step or the previous step redundant, do I need both debug and release?
	All builds succeed

Set Environment Variables (Are these needed if we copy the files over to the 
	OPENCV_DIR = 	     C:\OpenCV\opencv_bin
	OpenCV_INCLUDE_DIR = C:\OpenCV\opencv_bin\install\include
	OpenCV_LIBRARY_DIR = C:\Users\Tommy\source\repos\opencv_bin\install\x64\vc16\lib


Download OpenCVSharp 4.2.0 src from Releases
https://github.com/shimat/opencvsharp/archive/2020.02.08.zip
Extract to c:\OpenCV\opencvsharp_src

Create new directory called "win-x64" under c:\OpenCV\opencvsharp_src\opencv_files_420
Copy contents of "c:\OpenCV\opencv_bin\install" to "c:\OpenCV\opencvsharp_src\opencv_files_420\win-x64"
Rename "C:\OpenCV\opencvsharp_src\opencv_files_420\win-x64\x64\vc16\lib" to "staticlib" as per the includes defined in the 

Open "c:\OpenCV\opencvsharp_src\OpenCvSharp.sln" with Visual Studio 2019

I get four warnings but they all seem to refer to the UWP version of OpenCVSharpExtern
C:\OpenCV\opencvsharp_src\src\uwpOpenCvSharpExtern\uwpOpenCvSharpExtern.vcxproj : warning  : The build tools for Visual Studio 2019 (v142) cannot be found. Install Visual Studio 2019 (v142) to build using the Visual Studio 2019 (v142) build tools.
C:\OpenCV\opencvsharp_src\src\uwpOpenCvSharpExtern\uwpOpenCvSharpExtern.vcxproj : warning  : Platform 'Win32' referenced in the project file 'uwpOpenCvSharpExtern' cannot be found.
C:\OpenCV\opencvsharp_src\src\uwpOpenCvSharpExtern\uwpOpenCvSharpExtern.vcxproj : warning  : Platform 'ARM' referenced in the project file 'uwpOpenCvSharpExtern' cannot be found.
C:\OpenCV\opencvsharp_src\src\uwpOpenCvSharpExtern\uwpOpenCvSharpExtern.vcxproj : warning  : Platform 'x64' referenced in the project file 'uwpOpenCvSharpExtern' cannot be found.

Change build settings from "AnyCPU" to "x64" (leave config at "Debug")
Under Solution Explorer
	Expand "src"
	Right-click on "OpenCvSharpExtern" and select "Build"
	
Builds for about 30 seconds then I get a series of errors

Error	LNK1120	17 unresolved externals	OpenCvSharpExtern	C:\Users\Tommy\source\repos\opencvsharp_src\src\Debug\x64\OpenCvSharpExtern.dll	1	
Error	LNK2019	unresolved external symbol "public: class std::vector<double,class std::allocator<double> > __cdecl cv::img_hash::BlockMeanHash::getMean(void)const "
etc....

They are all from file img_hash.obj but I don't know if this is the problem file or if it's just the first file to be compiled so the first to hit whatever configuration issue I have?

If I try to change the build to "Release" I start getting error messages about missing .lib files, ade.lib, llmlmf.lib, etc... Some of these are present in the opencv_bin directory, some aren't.

**Comment by TechnikEmpire** [comment]
I'm not sure why no one messaged you back, this is pretty basic stuff for C++ people.

OpenCVSharp is compiled as what's called the "world" dll. Normally, OpenCV is compiled into several DLL's, unless you enable "world", which builds them all together into one (with the exception of FFMPEG).

So basically you just use CMAKE GUI (comes in the cmake tools installer), select the OpenCV folder (you don't need the contrib project), make up a build output folder and click "generate." This will puke visual studio projects into the "build" directory you enter in the cmake GUI.

Once you configure once (hit the configure button), start searching in the cmake GUI search bar for "MSMF" and "world". Check off these:

![image](https://user-images.githubusercontent.com/11234763/76291541-b1b6b380-6283-11ea-9699-26cf9d5ef4ec.png)

Then this:

![image](https://user-images.githubusercontent.com/11234763/76291587-cbf09180-6283-11ea-8990-bf175aff6cce.png)

Modify the install prefix to your liking (where the built DLL's etc will be copied to):

![image](https://user-images.githubusercontent.com/11234763/76291676-fa6e6c80-6283-11ea-9971-91ce149dc92a.png)


Click "Generate."

Then, open the build directory you made in cmake, open the SLN file there. Change to "Release" in configuration in Visual Studio. Then open the "build targets" section in the solution explorer and build "ALL_BUILD". When that's done, build "INSTALL", which will copy everything where you specified above (install prefix).

When you're finished, just rename the world DLL you compiled to the same DLL name OpenCVSharp uses (OpenCvSharpExtern.dll at this time) and drop it into your bin dir and uninstall opencvsharp-runtime nuget package. The managed C# side of things won't care that you completely changed the DLL on it (as long as API version is the same) because the C# Pinvoke stuff just looks for DLL + function name to load the library and get the function pointer.

**Comment by GilchristT** [comment]
@TechnikEmpire Jesse, thanks for taking the time to respond in such detail.

I had actually worked my way through compiling the DLL from this OpenCVSharp repo, it was a useful learning experience. I should really have come back here and noted that.

However this approach is much simpler and definitely the one I'll be using from now on.

Thanks again
