### ISSUE TITLE
OpenCvSharp usage with individual native DLLs

### ISSUE THREAD

**Issue by perkasthor** [shimat/opencvsharp#959]
Hello,

After a little googling, I did not find anything on the issue I'm facing.

We have a software that uses OpenCV both in native and managed code (via OpenCvSharp). The native part of our software uses individual OpenCV DLLs (core, imgproc, highgui, etc.), so in order to lighten our installation package I was wondering if OpenCvSharp can be complied to use the same individual DLLs.

In older OpenCvSharp versions, in the NativeMethods.cs file, we could configure the code to use the individual DLLs (via the array OpenCVDllNames), but I didn't find the same possibility in the latest source code (we'd like to use OpenCV 4.2.0).

So here is my question: is there any way to use the individual OpenCV DLLs instead of opencv_word?

Thanks in advance

**Comment by shimat** [comment]
Since the OpenCV C API is mostly obsolete, that old method is no longer available. I think it's possible if you customize and build your own native bindings (OpenCvSharpExtern.dll). OpenCvSharpExten links a lot of features, so you'll have to cut out the ones you don't need.

Honestly, it's not worth the effort, so I think it's easier to develop the wrapper by yourself, using C++/CLI or something similar.
