### ISSUE TITLE
Is there a way to make UMat available?

### ISSUE THREAD

**Issue by gaessanty** [shimat/opencvsharp#965]
# Summary of your issue
I want to use the GPU process.

# Environment
Windows x64, Nvidia GPU

# What did you do when you faced the problem?
First of all thanks to your open source project.
I wrote and used an image processing algorithm using OpenCvSharp.
However, recently, I would like to do GPU processing due to the limitation of computation speed.
When checking this repository, I know that it doesn't officially support UMat.
But I want to try and know what to start with.
Can you give me some advice on what I'm trying to do?

**Comment by shimat** [comment]
OpenCvSharp does not support GPUs due to the difficulty of distributing pre-built binaries and providing support to users. If you want to use OpenCV's GPU capabilities, you'll need to build the native binding DLL (OpenCvSharpExtern.dll) with GPU features yourself. 

Instead, I recommend using C++ or Python...
