### ISSUE TITLE
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.  ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies.

### ISSUE THREAD

**Issue by ccaneke** [shimat/opencvsharp#983]
# Summary of your issue
I'm getting the following error when I try to create a `Mat` using OpenCvSharp:

```
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies.
```
# Environment
MacOs 10.15

# What did you do when you faced the problem?
I tried both OpenCVSharp4 and OpenCVSharp3 nuget packages. And also installed the OpenCVSharp4.runtime.osx.10.15-x64. I tried both the x86 and x64 dlls. When trying OpenCVSharp3 I copied the OpenCvSharpExtern.dll and opencv_ffmpeg400_64.dll to the root of my project folder where my Program.cs file is.

**Comment by craftindo** [comment]
I have the same issue on win 7, VS 2019.
What I have tried:
1. I've installed all: 
opencvsharp4,opencvsharp4.windows,opencvsharp4.runtime.win, opencvsharp4.runtime.uwp
2. delete bin, obj folders and then re-build
3. re-install using nuget
4. using dependency walker, errors found:
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
DCOMP.DLL
IESHIMS.DLL
but according to some answers, it is a fake missing dll since win7.
None of all those work.



The same error:

System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: OpenCvSharpExtern assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) OpenCvSharp.NativeMethods.redirectError(OpenCvSharp.CvErrorCallback,intptr,intptr&)
  at OpenCvSharp.ExceptionHandler.RegisterExceptionCallback () [0x00006] in <f6706a6406854fd19202dd8568d0ec0a>:0 
  at OpenCvSharp.NativeMethods.LoadLibraries (System.Collections.Generic.IEnumerable`1[T] additionalPaths) [0x00007] in <f6706a6406854fd19202dd8568d0ec0a>:0 
  at OpenCvSharp.NativeMethods..cctor () [0x0003a] in <f6706a6406854fd19202dd8568d0ec0a>:0 
   --- End of inner exception stack trace ---
  at OpenCvSharp.Mat..ctor () [0x00006] in <f6706a6406854fd19202dd8568d0ec0a>:0 
  at TouchTrackingEffect.FingerPaintPage..ctor () [0x00061] in C:\Users\teffendi\source\repos\Isaac\TouchTrackingEffect\TouchTrackingEffect\FingerPaintPage.xaml.cs:61

**Comment by ChukwuemezieChristopherAneke** [comment]
@craftindo this is a serious problem, that according to issues I've seen date back as far as 2018 or earlier. No one seems to know a fix.

**Comment by craftindo** [comment]
hi Christopher,
I believe we;re missing something opencv.dll from c++. The question is how to produce that dll. 
<look at this youtube at min 6:14, it shows the project where he obtain the dll>

So, I've downloaded the source code opencv master but i can't even build it. It says can't include opencv2/opencv.hpp. I don't know how to build this source code c++ and c# together.
And, I am kind of stuck here.
Shall we collaborate together?

**Comment by ChukwuemezieChristopherAneke** [comment]
@craftindo you may be onto something. Sure we can collaborate on this. I don't think you would need to build both opencv and opencv sharp together. You probably just need the dlls of opencv c++, so just building them separately looks like the right way. You should get the opencv dlls after building opencv c++. After you've done this, let me know if you see the dlls in your local copy of the opencv repo, and also their names.

**Comment by craftindo** [comment]
Christopher,
In my case, my project is a xamarin project hence it uses netstandar2.0 framework. But, opencvsharp has a minimum requirement of  .net framework 4.0 or .net core 2.0, that's why it doesnt work. Check what framework are you using? I am still trying to integrate it into xamarin project. 
If you're on the same problem, Kawaian opencvsharp is showing example but I am still not succeed yet.

**Comment by yaoqs** [comment]
I have the same problem when I'm using opencvsharp4 on win10 vs2017 wpf.

code:   
`Mat src = new Mat();//error ocurs here`
output likes:
> 未经处理的异常:  System.TypeInitializationException: “OpenCvSharp.NativeMethods”的类型初始值设定项引发异常。 ---> System.DllNotFoundException: 无法加载 DLL“OpenCvSharpExtern”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
>    在 OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
>    在 OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
>    在 OpenCvSharp.NativeMethods..cctor()
>    --- 内部异常堆栈跟踪的结尾 ---
>    在 OpenCvSharp.NativeMethods.core_Mat_new1(IntPtr& returnValue)
>    在 OpenCvSharp.Mat..ctor()

**Comment by Bengkel** [comment]
My code on Windows 10 .Net Core C# runs correctly. When I build a docker image using this code I have the same issue.

Output
`The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.`

**Comment by ketankalia** [comment]
Hi,
I am in the process of moving a .NET core web api project from non-docker to a docker supported format.
Just like everybody, I have also used the awesome nuget package from @shimat  opencvsharp. 
For your reference, my csproj has following package references 
```
<PackageReference Include="OpenCvSharp4" Version="4.5.0.20201013" />
    <PackageReference Include="OpenCvSharp4.runtime.ubuntu.18.04-x64" Version="4.5.0.20201013" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.5.0.20201013" />
```
When I made a ubuntu 18.04 based docker image with my project restored on same, I ran into same errors as have been documented in this thread. Building opencvsharp from scratch was not an option I wanted to take. So I searched for opencvsharp docker image on docker hub and found docker image for OpenCVSharp v 4.5  tagged as `shimat/ubuntu18-dotnetcore3.1-opencv4.5.0`
On a hunch, I compared the size of libOpenCvSharpExtern.so (copied into /app/runtimes/ubuntu../native folder of my ubuntu image presumably by nuget) with libOpenCvSharpExtern.so in original opencvsharp docker image (which has 4.5 version).
The sizes were different. It looks like, the nuget does not get the correct libOpenCvSharpExtern.so file copied into /app/runtimes/ubuntu../native folder.

Following steps in dockerfile solved the above issue for me, but it created a 2 gigs plus docker image which is something I am trying to work on reducing now.

```
FROM docker.io/shimat/ubuntu18-dotnetcore3.1-opencv4.5.0:20201030 AS opencvsharp-env
WORKDIR .

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
# my dlls are copied to /app folder. I have removed those lines form this code snippet
WORKDIR /app
# Did ldd on libOpenCvSharpExtern and found most dependent files in below 2 directories so copied those over
COPY --from=opencvsharp-env usr/lib/ /usr/lib/   
COPY --from=opencvsharp-env lib/x86_64-linux-gnu/ /usr/lib/ 

# added these after trial and error
RUN cd .. && cd etc && mkdir fonts
COPY --from=opencvsharp-env etc/fonts/ /etc/fonts

# cleared originally provided libOpenCvSharpExtern.so file and copied one from opencvsharp docker image
RUN rm -rf /app/runtimes/ubuntu.18.04-x64/native/*
COPY --from=opencvsharp-env artifacts/ /app/runtimes/ubuntu.18.04-x64/native/

```
Hope it helps someone.

Thank you for the helpful info and advise provided here and thanks @shimat once again for this awesome package.

~Ketan

**Comment by monoqlo78** [comment]
I was able to solve it by using the 3.0 any cpu library. The usage environment is the Windows environment of Azure Function.
