### ISSUE TITLE
missing assembly 'PresentationCore'

### ISSUE THREAD

**Issue by jamminbean** [shimat/opencvsharp#990]
# Summary of your issue
When building a project with the latest (4.3.0.20200701) OpenCvSharp nuget package installed, I get an error stating, that the assembly 'PresentationCore, Version 4.0.0.0' is missing.
When unloading the project and replacing the packages for OpenCvSharp4 and OpenCvSharp4.Windows by an older version (4.3.0.20200421), the error disappears and I can successfully build the project.

# Environment
VS2019
Windows 10

# What did you do when you faced the problem?
I tried to use the Bitmap extension method bmp.ToMat()

## Example code:

```
using OpenCvSharp;
using OpenCvSharp.Extensions;
using System;
using System.Drawing;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Bitmap bmp = new Bitmap("test");
            Mat mat = bmp.ToMat();

        }
    }
}

```

**Comment by shimat** [comment]
Because of the following patch, you need to enable WPF if you are using a .NET Core project and some OpenCvSharp.Extension features.
https://github.com/shimat/opencvsharp/pull/954/files

.csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop"> <!-- enables WPF/WinForm -->

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF> <!-- enables WPF -->
 </PropertyGroup>

</Project>
```

If you're only using Mat.ToBitmap or Bitmap.ToMat, I find it puzzling that you would take this step. I'm working on a solution.
