### ISSUE TITLE
Can't work without OpenCvSharpExtern.pdb file

### ISSUE THREAD

**Issue by CCRcmcpe** [shimat/opencvsharp#992]
# Summary
When you delete the `OpenCvSharpExtern.pdb`, the program (with opencvsharp from nuget) will not work.
Note: The `OpenCvSharpExtern.pdb` is too large, so I tried to delete it when building release.
And the pdb just generated regardless with
```
<DebugType>none</DebugType>
<DebugSymbols>false</DebugSymbols>
```

# Environment
Windows 10, .NET 5.0 Preview 6

# What did you do when you faced the problem?
**Publish** the program with R2R enabled, delete the `OpenCvSharpExtern.pdb` and run the program.

## Output:

```
Error:
  An assembly specified in the application dependencies manifest (Auto Arknights CLI.deps.json) was not found:
    package: 'OpenCvSharp4.runtime.win', version: '4.3.0.20200701'
    path: 'runtimes/win-x64/native/OpenCvSharpExtern.pdb'
```

## What did you intend to be?
The program works properly without the .pdb file.

**Comment by eitanhs** [comment]
Introduced in 70e9d30570051742a78a08e439716cf94620e882

**Comment by shimat** [comment]
I added pdb to fix https://github.com/shimat/opencvsharp/issues/776

People sometimes complain that OpenCvSharp's file size is too large; OpenCvSharp includes a lot of features from the opencv_contrib, and that's one of the reasons why the file size is so large. Rarely will anyone need all the OpenCV features, but it's easier to handle this way.

I'm not really interested in reducing the file size of the library. I'm interested in making the library easy to use and easy to maintain. So I recommend to make your own wrapper if that's what you need.

**Comment by CCRcmcpe** [comment]
Got it. However I figured out how to make OpenCvSharp works without pdb file, with .deps.json editing magic (see [this](https://github.com/CCRcmcpe/Auto-Arknights/commit/4f30f079f2918f832dfd1a6c615597f41690cc1e)).

**Comment by eitanhs** [comment]
That's a shame dotnet CLI doesn't support a flag for excluding PDBs from the deps.json file when publishing the app :(
But that's totally out of scope..

**Comment by midwan** [comment]
Sorry to resurrect this issue, but I'm facing the same problem under a slightly different scenario:

We have .Net Core 3.1 apps that are packaged to AppX (using a separate Packaging project). When debugging the application locally, it works fine if started from the WPF project, but fails to start if the Package project is the Startup one.

I tracked this down to the missing .pdb file mentioned here, which I find a bit strange. The .pdb files were not included in the installer created as well, which caused the application to fail starting up at all, due to this.

Shouldn't the .pdb files be deployed/required only in Debug build scenarios? They are normally skipped in Release ones, but this requirement from OpenCvSharp makes it tricky to have an automated pipeline for CI/CD scenarios (without tinkering with the deps.json files like the example above).

**Comment by kaancfidan** [comment]
> Sorry to resurrect this issue, but I'm facing the same problem under a slightly different scenario:
> 
> We have .Net Core 3.1 apps that are packaged to AppX (using a separate Packaging project). When debugging the application locally, it works fine if started from the WPF project, but fails to start if the Package project is the Startup one.
> 
> I tracked this down to the missing .pdb file mentioned here, which I find a bit strange. The .pdb files were not included in the installer created as well, which caused the application to fail starting up at all, due to this.
> 
> Shouldn't the .pdb files be deployed/required only in Debug build scenarios? They are normally skipped in Release ones, but this requirement from OpenCvSharp makes it tricky to have an automated pipeline for CI/CD scenarios (without tinkering with the deps.json files like the example above).

We have exactly the same problem. We are also using MSIX to package a WPF app that depends on OpenCVSharp which results in `OpenCvSharpExtern.pdb` file not being copied into the installed app folder. Because it is listed in `deps.json`, application startup fails.

Why does OpenCvSharp explicitly depend on the pdb file to work? If there are no good reasons for it, can we remove it so it can be packaged by MSIX tools?

**Comment by shimat** [comment]
Thanks for your comments. I'm not familiar with the details of pdb and NuGet either, but the OpenCvSharpExtern.pdb is a debug symbol for C++, not C#, so it seems to be handled differently than the C# pdb. I'll try to remove it from the NuGet package. 
(I understand that C# pdb files (e.g. OpenCvSharp.pdb) are OK.)

**Comment by midwan** [comment]
@shimat 
Indeed, the problem is not with the rest of the pdb files, those are handled correctly.
Only the `OpenCvSharpExtern.pdb` requirement seems to be causing the problem.
